// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSYadDU8uaaz4wWXTPzI-nSwhbNmGcZYE',
    appId: '1:866638899649:web:9c46b86533656556bca740',
    messagingSenderId: '866638899649',
    projectId: 'ensan_app-61a83',
    authDomain: 'ensan_app-61a83.firebaseapp.com',
    storageBucket: 'ensan_app-61a83.firebasestorage.app',
    measurementId: 'G-527NGMVR9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx9num3xbr9RaFBaxH1m6PiY0UcXGjapM',
    appId: '1:866638899649:android:ef6e3bf88da3bcbbbca740',
    messagingSenderId: '866638899649',
    projectId: 'ensan_app-61a83',
    storageBucket: 'ensan_app-61a83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD20FtzrwSzX_R3xHltfjeV_PnmhMsNoLA',
    appId: '1:866638899649:ios:f03eb76298e872a7bca740',
    messagingSenderId: '866638899649',
    projectId: 'ensan_app-61a83',
    storageBucket: 'ensan_app-61a83.firebasestorage.app',
    iosBundleId: 'com.example.ensan_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD20FtzrwSzX_R3xHltfjeV_PnmhMsNoLA',
    appId: '1:866638899649:ios:f03eb76298e872a7bca740',
    messagingSenderId: '866638899649',
    projectId: 'ensan_app-61a83',
    storageBucket: 'ensan_app-61a83.firebasestorage.app',
    iosBundleId: 'com.example.ensan_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSYadDU8uaaz4wWXTPzI-nSwhbNmGcZYE',
    appId: '1:866638899649:web:a55aa238cc872873bca740',
    messagingSenderId: '866638899649',
    projectId: 'ensan_app-61a83',
    authDomain: 'ensan_app-61a83.firebaseapp.com',
    storageBucket: 'ensan_app-61a83.firebasestorage.app',
    measurementId: 'G-3W89LNH1L5',
  );
}
