// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8hL_kH4Rs9js8bF-LpXFWWi81FzwfvIY',
    appId: '1:605990225748:web:966be7605c0ae09092eac1',
    messagingSenderId: '605990225748',
    projectId: 'ensan-49bcb',
    authDomain: 'ensan-49bcb.firebaseapp.com',
    storageBucket: 'ensan-49bcb.firebasestorage.app',
    measurementId: 'G-16233RT0P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyvLdPnxe9OT-EwBTlwrnz_fSvvcJxygI',
    appId: '1:605990225748:android:f1c2ae301bb1de0e92eac1',
    messagingSenderId: '605990225748',
    projectId: 'ensan-49bcb',
    storageBucket: 'ensan-49bcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMx9x-Z-ogTG4pQevA3XpAGgqXJ9ViKxI',
    appId: '1:605990225748:ios:81004449f01de3fc92eac1',
    messagingSenderId: '605990225748',
    projectId: 'ensan-49bcb',
    storageBucket: 'ensan-49bcb.firebasestorage.app',
    iosBundleId: 'com.example.ensanApp',
  );
}
